### ISSUE TITLE
upgrade to nom 4

### ISSUE THREAD

**Issue by m4b** [dust-engine/dot_vox#14]
I am not familiar with nom at all, but upgrading to nom 4 will drop a lot of old transitive deps (many of which can't work with wasm targets); the major change in nom 4 appears to be `IResult -> Result` iiuc?

**Comment by m4b** [comment]
Here's a guide; again I don't understand much: https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md

**Comment by davidedmonds** [comment]
Thanks for the issue - I had previously tried to upgrade to nom 4, but there were [some changes to how `Incomplete` was working](https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md#dealing-with-incomplete-usage) which prevented me at the time. I think these issues might have been resolved, so will have a go at migrating some time soon.

**Comment by davidedmonds** [comment]
Published `v4.0.0` to crates.io, built with nom 4.1.

**Comment by m4b** [comment]
Wow that was fast, great work !
