### ISSUE TITLE
Release 5.2.0

### ISSUE THREAD

**Issue by kpreid** [dust-engine/dot_vox#42]
Could you release a version 5.2.0 to crates.io soon? I ask because:

* #37, restoring compatibility with stable Rust, has been merged but not released
* The last stable-compatible version, 4.1.0, now results in a future-compatibility warning in Rust 1.68.0 (due to using an old version of `nom`).

**Comment by PixelDust22** [comment]
Done! Thank you!

**Comment by kpreid** [comment]
It's working, and no more compatibility warnings. Thanks!
